steps:
  - label: 'Test'
    env:
      SEGMENT_CONTEXTS: snyk, aws-credentials
      SEGMENT_BUILDKITE_IMAGE: 'buildkite-agent-golang1.15'
    agents:
      queue: v1

    commands: |
      echo '--- Snyk'
      bk-snyk
      echo '--- Downloading Dependencies'
      go mod vendor
      echo '--- Running tests'
      go vet ./...
      go test -race ./...
